// FORE — lib/data/personas.ts
// Loads the static synthetic personas (TASK-004) generated by scripts/generate_data.py.
// These seed the shared financial_context when a demo persona is selected.

import type { Transaction } from "@/types/financialContext";

import priya from "@/data/personas/persona-priya.json";
import rahul from "@/data/personas/persona-rahul.json";
import aisha from "@/data/personas/persona-aisha.json";

export interface PersonaSeed {
  session_id: string;
  persona: string;
  monthly_income: number;
  income_bracket: string;
  city_tier: string;
  archetype_intended: string;
  transactions: Transaction[];
}

export const PERSONAS: PersonaSeed[] = [
  priya as PersonaSeed,
  rahul as PersonaSeed,
  aisha as PersonaSeed,
];

export function getPersona(sessionId: string): PersonaSeed | undefined {
  return PERSONAS.find((p) => p.session_id === sessionId);
}
